### ISSUE TITLE
"all-cyrillic.txt" не съдържа български думи, а комбинации от бг букви в по-голямата си част

### ISSUE THREAD

**Issue by AngelTs** [miglen/bulgarian-wordlists#10]
По-голямата част от "all-cyrillic.txt" не съдържа български думи, а комбинации от бг букви. Не е коректно да не го напишете на явно място!!!

**Comment by miglen** [comment]
Привет, мисля че вече е фикснато с този PR: https://github.com/miglen/bulgarian-wordlists/pull/11
